version: '2'
services:
  shinobi:
    container_name: 'Shinobi'
    build: .
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev/shm/Shinobi/streams:/dev/shm/streams
      - ./config:/config
      - ./database:/var/lib/mysql
      - ./customAutoLoad:/opt/shinobi/libs/customAutoLoad
      - ./videos:/opt/shinobi/videos
      - ./plugins:/opt/shinobi/plugins
    ports:
      - "8080:8080"
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvram:/dev/nvram
      - /dev/nvidia-caps:/dev/nvidia-caps